/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubscriptionPlan = IDL.Variant({
  'max' : IDL.Null,
  'pro' : IDL.Null,
  'growth' : IDL.Null,
  'starter' : IDL.Null,
  'basic' : IDL.Null,
});
export const Time = IDL.Int;
export const AiGenerationLog = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'inputImageBlobId' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'prompt' : IDL.Text,
  'outputImageBlobId' : IDL.Text,
});
export const DesignEntry = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'style' : IDL.Text,
  'roomType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CustomTheme = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'prompt' : IDL.Text,
});
export const StarredEntry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'imageUrl' : IDL.Text,
  'userPrincipal' : IDL.Principal,
  'prompt' : IDL.Text,
});
export const SubscriptionUsage = IDL.Record({
  'lastReset' : Time,
  'photosUsed' : IDL.Nat,
  'createdAt' : Time,
  'plan' : SubscriptionPlan,
  'videosUsed' : IDL.Nat,
});
export const PlanLimits = IDL.Record({
  'plan' : SubscriptionPlan,
  'videoLimit' : IDL.Nat,
  'price' : IDL.Nat,
  'photoLimit' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCustomTheme' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addStarredEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDodoPayment' : IDL.Func([IDL.Text, SubscriptionPlan], [], []),
  'createCheckoutSession' : IDL.Func(
      [SubscriptionPlan, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCustomTheme' : IDL.Func([IDL.Int], [], []),
  'deleteStarredEntry' : IDL.Func([IDL.Nat], [], []),
  'getAiGenerationLogCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAiGenerationLogs' : IDL.Func([], [IDL.Vec(AiGenerationLog)], ['query']),
  'getAiGenerationLogsReverse' : IDL.Func(
      [],
      [IDL.Vec(AiGenerationLog)],
      ['query'],
    ),
  'getAiGenerationLogsSorted' : IDL.Func(
      [],
      [IDL.Vec(AiGenerationLog)],
      ['query'],
    ),
  'getAllDesigns' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesignHistorySorted' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
  'getImage' : IDL.Func([ExternalBlob], [ExternalBlob], ['query']),
  'getMyCustomThemes' : IDL.Func([], [IDL.Vec(CustomTheme)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getMyStarredEntries' : IDL.Func([], [IDL.Vec(StarredEntry)], ['query']),
  'getMyStarredEntryCount' : IDL.Func([], [IDL.Nat], []),
  'getMySubscription' : IDL.Func([], [SubscriptionUsage], ['query']),
  'getPlanLimitsQuery' : IDL.Func([SubscriptionPlan], [PlanLimits], []),
  'getStarredEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StarredEntry)],
      ['query'],
    ),
  'getTotalStarredEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logAiGeneration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'recordPhotoUsage' : IDL.Func([], [], []),
  'recordVideoUsage' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegister' : IDL.Func([IDL.Text], [], []),
  'setUserPlan' : IDL.Func([IDL.Principal, SubscriptionPlan], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMyProfile' : IDL.Func([IDL.Text], [], []),
  'updateStarredEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Variant({
    'max' : IDL.Null,
    'pro' : IDL.Null,
    'growth' : IDL.Null,
    'starter' : IDL.Null,
    'basic' : IDL.Null,
  });
  const Time = IDL.Int;
  const AiGenerationLog = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'inputImageBlobId' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'prompt' : IDL.Text,
    'outputImageBlobId' : IDL.Text,
  });
  const DesignEntry = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'style' : IDL.Text,
    'roomType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CustomTheme = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'prompt' : IDL.Text,
  });
  const StarredEntry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'imageUrl' : IDL.Text,
    'userPrincipal' : IDL.Principal,
    'prompt' : IDL.Text,
  });
  const SubscriptionUsage = IDL.Record({
    'lastReset' : Time,
    'photosUsed' : IDL.Nat,
    'createdAt' : Time,
    'plan' : SubscriptionPlan,
    'videosUsed' : IDL.Nat,
  });
  const PlanLimits = IDL.Record({
    'plan' : SubscriptionPlan,
    'videoLimit' : IDL.Nat,
    'price' : IDL.Nat,
    'photoLimit' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCustomTheme' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addStarredEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDodoPayment' : IDL.Func([IDL.Text, SubscriptionPlan], [], []),
    'createCheckoutSession' : IDL.Func(
        [SubscriptionPlan, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCustomTheme' : IDL.Func([IDL.Int], [], []),
    'deleteStarredEntry' : IDL.Func([IDL.Nat], [], []),
    'getAiGenerationLogCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAiGenerationLogs' : IDL.Func([], [IDL.Vec(AiGenerationLog)], ['query']),
    'getAiGenerationLogsReverse' : IDL.Func(
        [],
        [IDL.Vec(AiGenerationLog)],
        ['query'],
      ),
    'getAiGenerationLogsSorted' : IDL.Func(
        [],
        [IDL.Vec(AiGenerationLog)],
        ['query'],
      ),
    'getAllDesigns' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesignHistorySorted' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
    'getImage' : IDL.Func([ExternalBlob], [ExternalBlob], ['query']),
    'getMyCustomThemes' : IDL.Func([], [IDL.Vec(CustomTheme)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getMyStarredEntries' : IDL.Func([], [IDL.Vec(StarredEntry)], ['query']),
    'getMyStarredEntryCount' : IDL.Func([], [IDL.Nat], []),
    'getMySubscription' : IDL.Func([], [SubscriptionUsage], ['query']),
    'getPlanLimitsQuery' : IDL.Func([SubscriptionPlan], [PlanLimits], []),
    'getStarredEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StarredEntry)],
        ['query'],
      ),
    'getTotalStarredEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logAiGeneration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'recordPhotoUsage' : IDL.Func([], [], []),
    'recordVideoUsage' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegister' : IDL.Func([IDL.Text], [], []),
    'setUserPlan' : IDL.Func([IDL.Principal, SubscriptionPlan], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMyProfile' : IDL.Func([IDL.Text], [], []),
    'updateStarredEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };