/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiGenerationLog {
  'id' : bigint,
  'createdAt' : Time,
  'inputImageBlobId' : string,
  'userPrincipal' : Principal,
  'prompt' : string,
  'outputImageBlobId' : string,
}
export interface CustomTheme {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'prompt' : string,
}
export interface DesignEntry {
  'principal' : Principal,
  'createdAt' : Time,
  'style' : string,
  'roomType' : string,
}
export type ExternalBlob = Uint8Array;
export interface PlanLimits {
  'plan' : SubscriptionPlan,
  'videoLimit' : bigint,
  'price' : bigint,
  'photoLimit' : bigint,
}
export interface StarredEntry {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'imageUrl' : string,
  'userPrincipal' : Principal,
  'prompt' : string,
}
export type SubscriptionPlan = { 'max' : null } |
  { 'pro' : null } |
  { 'growth' : null } |
  { 'starter' : null } |
  { 'basic' : null };
export interface SubscriptionUsage {
  'lastReset' : Time,
  'photosUsed' : bigint,
  'createdAt' : Time,
  'plan' : SubscriptionPlan,
  'videosUsed' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCustomTheme' : ActorMethod<[string, string], bigint>,
  'addDesign' : ActorMethod<[string, string], bigint>,
  'addStarredEntry' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDodoPayment' : ActorMethod<[string, SubscriptionPlan], string>,
  'createCheckoutSession' : ActorMethod<
    [SubscriptionPlan, string, string],
    string
  >,
  'deleteCustomTheme' : ActorMethod<[bigint], undefined>,
  'deleteStarredEntry' : ActorMethod<[bigint], undefined>,
  'getAiGenerationLogCount' : ActorMethod<[], bigint>,
  'getAiGenerationLogs' : ActorMethod<[], Array<AiGenerationLog>>,
  'getAiGenerationLogsReverse' : ActorMethod<[], Array<AiGenerationLog>>,
  'getAiGenerationLogsSorted' : ActorMethod<[], Array<AiGenerationLog>>,
  'getAllDesigns' : ActorMethod<[], Array<DesignEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesignHistorySorted' : ActorMethod<[], Array<DesignEntry>>,
  'getImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'getMyCustomThemes' : ActorMethod<[], Array<CustomTheme>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getMyStarredEntries' : ActorMethod<[], Array<StarredEntry>>,
  'getMyStarredEntryCount' : ActorMethod<[], bigint>,
  'getMySubscription' : ActorMethod<[], SubscriptionUsage>,
  'getPlanLimitsQuery' : ActorMethod<[SubscriptionPlan], PlanLimits>,
  'getStarredEntries' : ActorMethod<[Principal], Array<StarredEntry>>,
  'getTotalStarredEntryCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleDodoWebhook' : ActorMethod<[string, string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logAiGeneration' : ActorMethod<[string, string, string], undefined>,
  'recordPhotoUsage' : ActorMethod<[], undefined>,
  'recordVideoUsage' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[string], undefined>,
  'setUserPlan' : ActorMethod<[Principal, SubscriptionPlan], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMyProfile' : ActorMethod<[string], undefined>,
  'updateStarredEntry' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];